### ISSUE TITLE
Unreliable LaTeX equation rendering

### ISSUE THREAD

**Issue by borlafgis** [quarto-dev/jupyterlab-quarto#3]
I've been tying the extension, and it works great for the most part, but I am having issues with LaTeX expressions: sometimes they are not rendered or they are not correctly rendered.

When they do not render (they do not seem to be recognized by mathjax), there are some things that may be clues of what is happening:

- LaTeX blocks are represented as surrounded by  \\[ and  \\] or (\\( \\)), even though I only use '$' at the start/end.

![image](https://github.com/quarto-dev/jupyterlab-quarto/assets/28223797/25c65ec3-eb10-487a-a678-b752c0ee78ba)

![image](https://github.com/quarto-dev/jupyterlab-quarto/assets/28223797/0281ea24-aa32-4ea4-b230-4bcc0f220d68)

- If I refresh the page sometimes the rendering comes back
- Moving markdown cells seems to cause breaks in the rendering
- Disabling the extension restores everything

When they do not render correctly, a right click > math settings > restore defaults allows the equations to be properly visualized

Broken
![image](https://github.com/quarto-dev/jupyterlab-quarto/assets/28223797/35ad232a-ff3e-4575-a17a-1af5c199e2f4)

Re-rendered:
![image](https://github.com/quarto-dev/jupyterlab-quarto/assets/28223797/34a2def8-a7e0-410a-a01b-f1d6b3e0fa37)

**Comment by borlafgis** [comment]
I updated jupyterlab-quarto to version 0.3.2 and then to 0.3.3. Everything seemed to work ok for a while, but now the issues are back:

Some cells are rendered wrong (if I reset mathjax to defaults they come back)
![image](https://github.com/quarto-dev/jupyterlab-quarto/assets/28223797/4ebfb9fa-2cd1-4e3b-addf-03fc242c96ff)

Some cells do not render at all no matter what I do
![image](https://github.com/quarto-dev/jupyterlab-quarto/assets/28223797/3384e15b-1684-4706-aa65-becbec38b07d)

**Comment by dragonstyle** [comment]
I actually don't have much of a theory, unfortunately. When the notebook loads, we looks through the cells for math to be typeset and then run the MathJax typesetter on those elements. 0.3.3 added an observer that will properly do this when you add new markdown cells to the notebook. But I'm not sure why it would be so intermittent  for you :(.

If you can narrow it down or share a notebook when you have it in a state that reproduces it, I could use that to see if I could reproduce the issue (which would make it much easier to fix). In addition, there could be error in the browser console (e.g. a javascript error) that could be helpful- the next time you see a failure to typeset could you check that (under your browser developer tools)?

**Comment by borlafgis** [comment]
I think I found an example of a cell that refuses to render. It is in the section "time domain statistics" (the notebook is inside the zip)

[0issues.zip](https://github.com/quarto-dev/jupyterlab-quarto/files/14620729/0issues.zip)

Miniforge console does not show any noticeable errors

**Comment by dragonstyle** [comment]
Here's what I see when I run it locally :(. It may be a particular state that you have some way to get to (e.g. editing sequence or workflow of some kind). It also could be interaction with other Jupyter lab extensions, perhaps? Trying to think of other possibly related factors....

<img width="972" alt="Screenshot 2024-03-16 at 5 14 12 PM" src="https://github.com/quarto-dev/jupyterlab-quarto/assets/261654/1ec42dbb-df33-4287-8b4b-67e2b0eba482">

**Comment by borlafgis** [comment]
I will keep on trying. I will check to see if it is related to the enviroment, or something that has been left in a weird state
Thanks a lot for your time!

**Comment by tmatthias29** [comment]
I have nothing to add except that I've run into this issue and started pulling out hair to figure out what was going run. It's definitely the jupyterlab-quarto extension changing the LaTeX/MathJax output, but I don't know nearly enough about this to comment any further.

I setup a really simple issue to confirm my issue. Basically, the following renders correctly in a Jupyter Notebook _and_ Jupyter Lab environment, without `jupyterlab-extension` installed:

<img width="318" alt="Screenshot 2024-04-04 at 2 53 42 PM" src="https://github.com/quarto-dev/jupyterlab-quarto/assets/2508250/515c52ae-c04e-495e-85ab-a2bc94d25383">

But with `jupyterlab-extension` installed, it seems like the output will drop random variables/symbols. In this case, it's dropping symbols when I'm using the `$x^2$` notation, but this seems to be an issue even when rendering SymPy/LaTeX output as well (i.e. with Display). It might be related to flipping the order around, see the second image.

<img width="337" alt="Screenshot 2024-04-04 at 2 51 37 PM" src="https://github.com/quarto-dev/jupyterlab-quarto/assets/2508250/5cf52bfa-c09f-4a21-89e7-b71581c78879">

<img width="333" alt="Screenshot 2024-04-04 at 2 55 28 PM" src="https://github.com/quarto-dev/jupyterlab-quarto/assets/2508250/a0e0dd0b-3c3b-498d-a2b7-9074df49b0d8">

Considering how useful the extension is, would be great to have this resolved, but I guess for now I'll need to remove the extension when I need to render MathJax.

**Comment by tmatthias29** [comment]
Turns out, I think the issue is also (or maybe only) caused by having Markdown cells in the notebook when the extension is installed.

**Comment by BigFlagBurito** [comment]
I have the same problem.
Have any of you found a possible solution?

**Comment by drmikecooke** [comment]
I have uninstalled quarto (which I installed to see if it was useful; for me, not really) since it stopped me rendering matrix equations in markdown. This, for example, the first in a sequence of pmatrices:

$$\begin{pmatrix}
u_x\\
v_x
\end{pmatrix}=
\begin{pmatrix}
1 & x/p\\
0 & 1
\end{pmatrix}
\begin{pmatrix}
u_0\\
v_0
\end{pmatrix}.$$

rendered up to the last double dollar, which it rendered as a double dollar, but then continued for the rest of the document as if the display math-mode was not closed with the text running off the page.

This was in an md file, and I was using the preview function.

By the way, the parentheses on the preview tab here don't properly render, but just give normal-sized rather than the extended form. The mathjax latex rendering github uses, doesn't seem correct. I have used mathjax in the past to render and didn't seem to have a problem.
