### ISSUE TITLE
setup.py and ui-tests included in wheel

### ISSUE THREAD

**Issue by lahwaacz** [quarto-dev/jupyterlab-quarto#5]
The `pyproject.toml` file includes `setup.py` and `ui-tests` in the wheel:
https://github.com/quarto-dev/jupyterlab-quarto/blob/4a14120293910fe2877c6437397aedb9aaab4c9c/pyproject.toml#L40C1-L40C91

They appear directly under `site-packages` where they pollute the global module space (the names don't associate to jupyterlab-quarto):
```
python3.11/site-packages/jupyterlab-quarto/
python3.11/site-packages/jupyterlab-quarto/__init__.py
python3.11/site-packages/jupyterlab-quarto/_version.py
python3.11/site-packages/jupyterlab_quarto-0.3.2.dist-info/
python3.11/site-packages/jupyterlab_quarto-0.3.2.dist-info/METADATA
python3.11/site-packages/jupyterlab_quarto-0.3.2.dist-info/RECORD
python3.11/site-packages/jupyterlab_quarto-0.3.2.dist-info/WHEEL
python3.11/site-packages/jupyterlab_quarto-0.3.2.dist-info/licenses/
python3.11/site-packages/jupyterlab_quarto-0.3.2.dist-info/licenses/LICENSE
python3.11/site-packages/setup.py
python3.11/site-packages/ui-tests/
python3.11/site-packages/ui-tests/jupyter_server_test_config.py
```

**Comment by lahwaacz** [comment]
Ugh, you probably forgot to commit the change - the v0.3.3 tag is on a [commit from yesterday](https://github.com/quarto-dev/jupyterlab-quarto/commit/4a14120293910fe2877c6437397aedb9aaab4c9c)... :shrug:

**Comment by dragonstyle** [comment]
TY! I had just forgotten to push my changes. I've updated the tag.
